export const QuestionTip1 =
  'We ask this to collect basic demographics for evaluation and quality improvement.';
export const QuestionTip2 =
  'You can answer this question and share it with your healthcare team if you choose.' +
  ' CareHub administrators will not be able to see your answer.';
export const QuestionTip3 =
  'We ask this to tailor the resources, programs and services that are suggested for you,' +
  ' and to collect basic demographics for evaluation and quality improvement.';
export const QuestionTip4 =
  'We ask this to tailor the resources, programs and services that are suggested for you.';

export const QuestionTip5 = 'We ask this to tailor your CareHub.';

export const RequiredAlert1 =
  'Please note that the information, resources, programs and services generated by CareHub' +
  ' are for caring for adults. If you are caring for a child or someone under 18, please' +
  ' visit CaringTogether.life for information, resources, programs and services for caring' +
  ' for a seriously ill child.';
//http://www.caringtogether.life/

export const YourAges = [
  'Under 12',
  '12 - 18',
  '19 - 44',
  '45 - 64',
  '65 - 79',
  '80 - 89',
  '90 and over',
];
export const TimeHealthIssues = [
  '6 months or less',
  '6 - 12 months',
  'Over a year',
];

export const CareMonths = ['0 - 6 months', '6 - 12 months', 'Over 1 year'];

export const CareDays = ['1 - 2 days', '3 - 4 days', '4 - 6 days', '7 days'];

export const CareHours = [
  'Less than 1 hour',
  '1 - 3 hours',
  '3 - 6 hours',
  'Over 6 hours',
];

export const Answers = ['Yes', 'No'];

export const WorkTimes = ['Yes - Full time', 'Yes - Part time', 'No'];

export const CarePeople = [
  'Partner or Spouse',
  'Parent',
  'Friend',
  'Sibling',
  'In-law',
  'Child',
  'Grandchild',
];

export const BannerList = [
  {title: 'Default', url: '/img/banner/default.jpg'},
  {title: 'Bird', url: '/img/banner/bird.jpg'},
  {title: 'Seaside', url: '/img/banner/1.jpg'},
  {title: 'Flower', url: '/img/banner/2.jpg'},
  {title: 'Sunrise', url: '/img/banner/3.jpg'},
  {title: 'Sky', url: '/img/banner/4.jpg'},
  {title: 'Nature', url: '/img/banner/5.jpg'},
  {title: 'Forest', url: '/img/banner/6.jpg'},
  {title: 'Other', url: '/img/banner/7.jpg'},
];

const likeLearnMore = 'Would you like to learn more about it?';
export const patientQuestionSuggestions = {
  mainIssues: {
    title: likeLearnMore,
    // eslint-disable-next-line
    condition: function condition(value) {
      if (
        value &&
        value.filter((mi) => mi && mi.toLowerCase().includes('lung')).length > 0
      ) {
        return 'value';
      }
    },
    options: { value: [3] },
  },
  minorIssues: {
    title: likeLearnMore,
    // eslint-disable-next-line
    condition: function condition(value) {
      if (
        value &&
        value.filter((mi) => mi && mi.toLowerCase().includes('insomnia'))
          .length > 0
      ) {
        return 'value';
      }
    },
    options: { value: [44, 54] },
  },
  childrenAge: {
    title: likeLearnMore,
    // eslint-disable-next-line
    condition: function condition(value) {
      if (
        value &&
        (value.includes('1') || value.includes('2') || value.includes('3'))
      ) {
        return '1';
      }
    },
    options: { '1': [52], '2': [52], '3': [52] },
  },
};

export const caregiverQuestionSuggestions = {
  haveChildren: {
    title: likeLearnMore,
    options: { '1': [52] },
  },
  childrenAge: {
    title: likeLearnMore,
    // eslint-disable-next-line
    condition: function condition(value) {
      if (
        value &&
        (value.includes('1') || value.includes('2') || value.includes('3'))
      ) {
        return '1';
      }
    },
    options: { '1': [52], '2': [52], '3': [52] },
  },
};

export const commonQuestionSuggestions = {
  haveChildren: {
    title: likeLearnMore,
    options: { '1': [52] },
  },
  childrenAge: {
    title: likeLearnMore,
    // eslint-disable-next-line
    condition: function condition(value) {
      if (
        value &&
        (value.includes('1') || value.includes('2') || value.includes('3'))
      ) {
        return '1';
      }
    },
    options: { '1': [52], '2': [52], '3': [52] },
  },
};
